== {{name}}

Project {{name}} generated from library template https://github.com/redstarssystems/lib-template.git.

First, run `make requirements` once to install necessary tools (MacOS only).

Run `make` to show help for project workflow.

Check file `pbuild.edn` to see project building tool configuration.

== Project commands

To configure project workflow use `Makefile`.

Run `make` or `make info` to see additional information.

List of available `make` commands:

* requirements  - install necessary tools. MacOS only! (lint, format, jenv, direnv, etc.)
* clean         - clear target folder
* repl          - run Clojure REPL
* javac         - compile java sources
* build         - build jar file (as library)
* install       - install jar file (library) to local .m2
* conflicts     - show class conflicts (if any)
* outdated      - check for outdated dependencies
* deploy        - deploy jar file (library) to remote repository
* release       - release artifact
* test          - run tests
* bump          - bump version artifact in build file. Parameter should be one of: major, minor, patch, alpha, beta, rc
* format        - format source code
* lint          - lint source code
* help          - show help


## License

Copyright © {{year}} {{user}}

Distributed under the Eclipse Public License 2.0 or (at your option) any later version.
