== Library template for clj-new

This library template based on `clj-new` helps to quick start new Clojure project using `clojure` tool.

It gives you configured: environment variables control, editor configuration, linter, formatter, tests.

Adapted for Intellij IDEA, but can be used with any editor.

Library template can perform following tasks:

* build jar
* compile java sources
* create pom
* sign jar file
* local install to .m2
* deploy jar to remote repo (eg. clojars, maven central, etc)
* run tests using kaocha

See also:

* https://github.com/redstarssystems/app-template[Application template]
* https://github.com/redstarssystems/web-template[Web template]

**Warning**: tested on Mac & linux.

== Usage

1. Install Clojure tools https://clojure.org/guides/getting_started

[source,bash]
----
brew install clojure/tools/clojure
----

2. Install latest clj-new (0.8.6+) from https://github.com/seancorfield/clj-new as :new alias to ~/.clojure/deps.edn.
(clj-new 0.8.5 and lower may have errors very rarely.)

3. (optional) Clone this repo to your local folder (e.g. ~/projects/lib-template)

4. Create new project from local template (step 3 is required):
+
`$ clj -M:new ~/projects/lib-template::lib-template my.example/lib01` 
+
or, create new project from Github template: 
+
`$ clj -M:new https://github.com/redstarssystems/lib-template@a4bd67780232276f98628d34e5acc5ec4ef810cf my.example/lib01`

5. See README.adoc in a root of created project folder.

== License

Copyright © 2020 Mike Ananev

Distributed under the Eclipse Public License 2.0 or (at your option) any later version.
